#pragma once

#include <vector>
#include "BuildStep.hpp"


using namespace std;

struct BuildLogResult {
	int executionTime;
	int result;
	bool success;

};
class BuildListTester
{


public:
	BuildListTester();
	~BuildListTester();

	vector<string>  splitString(string input, char splitter);
	// Returns the Log generated by the execution of the given Build-List
	vector<string> testBuildList(vector<BuildStep*> list);  

	// Analzes the Log to receive key-figures
	BuildLogResult analyzeBuildLog(vector<string>log, string entity, string mode);

	// Writes Log to file
	void writeLog(vector<string> log, string filename);

	// Writes BuildList to file
	void writeBuildList(vector<BuildStep*> list, string filename);

};
